[platformio]
default_envs = picture-badge

[env:picture-badge]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 32MB
board_upload.maximum_size = 3145728
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = vendor/waveshare/examples/arduino/libraries
lib_ldf_mode = chain
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -Ivendor/waveshare/examples/arduino/libraries/Mylibrary
